import { useEffect, useMemo, useState } from "react";
import { getAdminDashboard, getAdminUsers, getAdminDatasets, getAdminSystem, getAdminActivity, setBusinessStatus, deleteBusiness, getBusinessDatasets, getDatasetDetails, deleteDataset } from "../services/adminApi";
import "./AdminPanel.css";

const sections = ["Overview", "Businesses", "Datasets", "Activity", "System"];

export default function AdminPanel({ token, account, onLogout }) {
  const [section, setSection] = useState("Overview");
  const [dashboard, setDashboard] = useState(null), [users, setUsers] = useState([]), [datasets, setDatasets] = useState([]), [activity, setActivity] = useState([]), [system, setSystem] = useState(null);
  const [selectedBusiness, setSelectedBusiness] = useState(null), [businessDatasets, setBusinessDatasets] = useState([]), [selectedDataset, setSelectedDataset] = useState(null), [previewRows, setPreviewRows] = useState([]);
  const [businessSearch, setBusinessSearch] = useState(""), [businessStatus, setBusinessStatusFilter] = useState("all"), [datasetSearch, setDatasetSearch] = useState(""), [datasetFormat, setDatasetFormat] = useState("all");
  const [loading, setLoading] = useState(true), [working, setWorking] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");

  async function refreshAdminData() {
    setLoading(true); setError("");
    const results = await Promise.allSettled([getAdminDashboard(token), getAdminUsers(token), getAdminDatasets(token), getAdminActivity(token), getAdminSystem(token)]);
    const [d,u,ds,a,s] = results, errors = [];
    if (d.status === "fulfilled") setDashboard(d.value.data); else errors.push(`Overview: ${d.reason.message}`);
    if (u.status === "fulfilled") setUsers(u.value.data.users || []); else errors.push(`Businesses: ${u.reason.message}`);
    if (ds.status === "fulfilled") setDatasets(ds.value.data.datasets || []); else errors.push(`Datasets: ${ds.reason.message}`);
    if (a.status === "fulfilled") setActivity(a.value.data.activity || []); else errors.push(`Activity: ${a.reason.message}`);
    if (s.status === "fulfilled") setSystem(s.value.data); else errors.push(`System: ${s.reason.message}`);
    setError(errors.join(" | ")); setLoading(false);
  }
  useEffect(() => { refreshAdminData(); }, [token]);

  const businesses = useMemo(() => users.filter(x => x.role !== "admin").filter(x => `${x.businessName} ${x.email}`.toLowerCase().includes(businessSearch.toLowerCase())).filter(x => businessStatus === "all" || x.accountStatus === businessStatus), [users,businessSearch,businessStatus]);
  const visibleDatasets = useMemo(() => datasets.filter(x => `${x.fileName} ${x.businessName} ${x.email || ""}`.toLowerCase().includes(datasetSearch.toLowerCase())).filter(x => datasetFormat === "all" || String(x.fileFormat).toLowerCase() === datasetFormat), [datasets,datasetSearch,datasetFormat]);
  const formats = [...new Set(datasets.map(x => String(x.fileFormat || "").toLowerCase()).filter(Boolean))];

  async function handleStatusChange(user) { const next = user.accountStatus === "disabled" ? "active" : "disabled"; if (!window.confirm(`${next === "disabled" ? "Disable" : "Enable"} ${user.businessName}? ${next === "disabled" ? "Their protected application access will be blocked." : "Their application access will be restored."}`)) return; setWorking(true); setError(""); try { await setBusinessStatus(token,user.id,next); setMessage(`${user.businessName} is now ${next}.`); await refreshAdminData(); } catch(e){setError(e.message)} finally{setWorking(false)} }
  async function handleDeleteBusiness(user) { if (window.prompt(`PERMANENT ACTION\nDeleting ${user.businessName} also deletes its datasets and stored rows.\nType DELETE to continue:`) !== "DELETE") return; setWorking(true); setError(""); try { await deleteBusiness(token,user.id); if(selectedBusiness?.id===user.id){setSelectedBusiness(null);setBusinessDatasets([])} setMessage(`${user.businessName} and its ingestion data were permanently deleted.`); await refreshAdminData(); } catch(e){setError(e.message)} finally{setWorking(false)} }
  async function handleViewBusiness(user) { setSelectedBusiness(user); setError(""); try { const r=await getBusinessDatasets(token,user.id); setBusinessDatasets(r.data.datasets||[]); } catch(e){setError(e.message)} }
  async function handleViewDataset(dataset) { setError(""); try { const r=await getDatasetDetails(token,dataset.id); setSelectedDataset(r.data.dataset); setPreviewRows(r.data.previewRows||[]); } catch(e){setError(e.message)} }
  async function handleDeleteDataset(dataset) { if(window.prompt(`PERMANENT ACTION\nDeleting ${dataset.fileName} removes all persisted rows for this ingestion.\nType DELETE to continue:`)!=="DELETE") return; setWorking(true);setError("");try{await deleteDataset(token,dataset.id);if(selectedDataset?.id===dataset.id){setSelectedDataset(null);setPreviewRows([])}setMessage(`${dataset.fileName} was permanently deleted.`);await refreshAdminData();if(selectedBusiness){const r=await getBusinessDatasets(token,selectedBusiness.id);setBusinessDatasets(r.data.datasets||[])}}catch(e){setError(e.message)}finally{setWorking(false)} }

  const stats=dashboard?.stats||{}, formatDate=v=>v?new Date(v).toLocaleString():"—", number=v=>Number(v||0).toLocaleString(), detailText=v=>{if(!v)return"—";if(typeof v==="string"){try{return JSON.stringify(JSON.parse(v))}catch{return v}}return JSON.stringify(v)};
  return <div className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><div className="admin-mark">A</div><div><strong>Alpha</strong><span>Administration</span></div></div><p className="admin-nav-label">Control center</p><nav>{sections.map(item=><button key={item} className={section===item?"admin-nav active":"admin-nav"} onClick={()=>setSection(item)}>{item}</button>)}</nav><div className="admin-side-status"><i/>Application controls</div></aside><main className="admin-main"><header className="admin-topbar"><div><span className="admin-kicker">PROJECT ALPHA</span><strong>Admin Control Center</strong></div><div className="admin-account"><div className="admin-avatar">{(account?.businessName||"AD").slice(0,2).toUpperCase()}</div><div><strong>{account?.businessName||account?.email||"Administrator"}</strong><span>Administrator</span></div><button onClick={onLogout}>Sign out</button></div></header><div className="admin-content">
    {loading&&<div className="admin-notice">Loading live Project Alpha data...</div>}{message&&<div className="admin-success">{message}</div>}{error&&<div className="admin-error">{error}</div>}
    {section==="Overview"&&<><PageTitle title="Application overview" text="Live operational status and shortcuts into the controls that manage Project Alpha."/><div className="stat-grid"><Stat label="Business accounts" value={number(stats.businessAccounts)} detail={`${number(stats.disabledAccounts)} disabled`}/><Stat label="Datasets" value={number(stats.totalUploads)} detail="Persisted ingestions"/><Stat label="Rows stored" value={number(stats.totalRows)} detail="Actual database rows"/><Stat label="Admin actions" value={number(activity.length)} detail="Recent audit entries loaded"/></div><div className="quick-actions"><button onClick={()=>setSection("Businesses")}>Manage businesses</button><button onClick={()=>setSection("Datasets")}>Manage datasets</button><button onClick={()=>setSection("Activity")}>Review activity</button></div><section className="admin-card"><CardTitle title="Recent datasets" note="Latest ingestion activity across businesses"/><Table headers={["Dataset","Business","Shape","Status","Uploaded","Control"]} rows={(dashboard?.recentUploads||[]).map(x=>[x.fileName,x.businessName,`${number(x.rowCount)} × ${number(x.columnCount)}`,x.status,formatDate(x.createdAt),<button className="admin-action" onClick={()=>{setSection("Datasets");handleViewDataset(x)}}>Open</button>])}/></section></>}
    {section==="Businesses"&&<><PageTitle title="Business Management" text="Search, inspect and control business access to Project Alpha."/><Filters><input placeholder="Search business or email" value={businessSearch} onChange={e=>setBusinessSearch(e.target.value)}/><select value={businessStatus} onChange={e=>setBusinessStatusFilter(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="disabled">Disabled</option></select><span>{businesses.length} shown</span></Filters><section className="admin-card"><Table headers={["Business","Email","Status","Uploads","Created","Controls"]} rows={businesses.map(x=>[x.businessName,x.email,<Status value={x.accountStatus}/>,number(x.uploadCount),formatDate(x.createdAt),<div className="admin-actions"><button className="admin-action" onClick={()=>handleViewBusiness(x)}>View</button><button className="admin-action" disabled={working} onClick={()=>handleStatusChange(x)}>{x.accountStatus==="disabled"?"Enable":"Disable"}</button><button className="admin-action danger" disabled={working} onClick={()=>handleDeleteBusiness(x)}>Delete</button></div>])}/></section>{selectedBusiness&&<section className="admin-card control-detail"><CardTitle title={selectedBusiness.businessName} note={`${selectedBusiness.email} · ${selectedBusiness.accountStatus}`}/><Table headers={["Dataset","Format","Rows","Columns","Status","Uploaded","Control"]} rows={businessDatasets.map(x=>[x.fileName,x.fileFormat,number(x.rowCount),number(x.columnCount),x.status,formatDate(x.createdAt),<button className="admin-action" onClick={()=>{setSection("Datasets");handleViewDataset(x)}}>Open</button>])}/></section>}</>}
    {section==="Datasets"&&<><PageTitle title="Dataset Management" text="Find, inspect and manage persisted Module 02 datasets."/><Filters><input placeholder="Search dataset, business or email" value={datasetSearch} onChange={e=>setDatasetSearch(e.target.value)}/><select value={datasetFormat} onChange={e=>setDatasetFormat(e.target.value)}><option value="all">All formats</option>{formats.map(f=><option key={f} value={f}>{f.toUpperCase()}</option>)}</select><span>{visibleDatasets.length} shown</span></Filters><section className="admin-card"><Table headers={["Dataset","Business","Format","Rows","Columns","Status","Uploaded","Controls"]} rows={visibleDatasets.map(x=>[x.fileName,x.businessName,x.fileFormat,number(x.rowCount),number(x.columnCount),x.status,formatDate(x.createdAt),<div className="admin-actions"><button className="admin-action" onClick={()=>handleViewDataset(x)}>Preview</button><button className="admin-action danger" disabled={working} onClick={()=>handleDeleteDataset(x)}>Delete</button></div>])}/></section>{selectedDataset&&<DatasetDetail dataset={selectedDataset} rows={previewRows} number={number} formatDate={formatDate} onDelete={()=>handleDeleteDataset(selectedDataset)}/>}</>}
    {section==="Activity"&&<><PageTitle title="Admin Activity" text="Persistent audit history for administrative changes."/><section className="admin-card"><Table headers={["Action","Administrator","Target","Details","Time"]} rows={activity.map(x=>[String(x.action).replaceAll("_"," "),x.adminName,`${x.targetType} #${x.targetId??"—"}`,<span className="audit-details" title={detailText(x.details)}>{detailText(x.details)}</span>,formatDate(x.createdAt)])}/></section></>}
    {section==="System"&&<><PageTitle title="System" text="Runtime health, upload configuration and secondary project readiness information."/><div className="system-grid"><section className="admin-card"><CardTitle title="Runtime" note="Current environment"/><Info label="Backend" value={system?.backend}/><Info label="Database" value={system?.database}/><Info label="Accepted files" value={system?.supportedFormats?.join(", ")}/><Info label="Upload limit" value={`${system?.maximumUploadMb||10} MB`}/></section><section className="admin-card"><CardTitle title="Project status" note="Development reference only"/><Roadmap modules={system?.modules||[]}/></section></div></>}
  </div></main></div>;
}

function DatasetDetail({dataset,rows,number,formatDate,onDelete}){const parsed=rows.map(r=>({rowNumber:r.rowNumber,data:parseData(r.rawData)})), headers=[...new Set(parsed.flatMap(r=>Object.keys(r.data||{})))];return <section className="admin-card control-detail"><CardTitle title={dataset.fileName} note={`${dataset.businessName||"Unknown business"} · ${dataset.fileFormat}`}/><div className="detail-grid"><Info label="Rows" value={number(dataset.rowCount)}/><Info label="Columns" value={number(dataset.columnCount)}/><Info label="Status" value={dataset.status}/><Info label="Uploaded" value={formatDate(dataset.createdAt)}/></div><div className="detail-toolbar"><strong>First 25 persisted rows</strong><button className="admin-action danger" onClick={onDelete}>Delete dataset</button></div>{headers.length?<div className="admin-table-wrap"><table className="admin-table preview-table"><thead><tr><th>#</th>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{parsed.map(r=><tr key={r.rowNumber}><td>{r.rowNumber}</td>{headers.map(h=><td key={h}>{displayCell(r.data?.[h])}</td>)}</tr>)}</tbody></table></div>:<p>No stored rows found.</p>}</section>}
function parseData(v){try{return typeof v==="string"?JSON.parse(v):v||{}}catch{return{value:String(v)}}} function displayCell(v){if(v==null)return"—";return typeof v==="object"?JSON.stringify(v):String(v)}
function Filters({children}){return <div className="admin-filters">{children}</div>} function Roadmap({modules}){return <div className="roadmap">{modules.map(m=><div key={m.id} className={`roadmap-item ${m.status}`}><b>{String(m.id).padStart(2,"0")}</b><div><strong>{m.name}</strong><span>{m.status==="completed"?"Operational":"Upcoming"}</span></div></div>)}</div>} function Status({value}){return <span className={`status-badge ${value}`}>{value||"active"}</span>} function Stat({label,value,detail}){return <div className="stat-card"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>} function CardTitle({title,note}){return <div className="card-title"><div><h2>{title}</h2><p>{note}</p></div></div>} function PageTitle({title,text}){return <div className="admin-heading compact"><div><span>Administration</span><h1>{title}</h1><p>{text}</p></div></div>} function Info({label,value}){return <div className="info-row"><span>{label}</span><strong>{value||"—"}</strong></div>} function Table({headers,rows}){return <div className="admin-table-wrap"><table className="admin-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c??"—"}</td>)}</tr>):<tr><td colSpan={headers.length} className="empty-cell">No matching records found.</td></tr>}</tbody></table></div>}
