import { useEffect, useState } from "react";
import { Area, AreaChart, CartesianGrid, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { getAnalytics } from "../services/analyticsApi";
import AnalyticsFilters from "../components/analytics/AnalyticsFilters";
import { formatPercent, titleCase } from "../utils/formatters";

export default function InsightsPage({ token }) {
  const [filters, setFilters] = useState({ preset: "monthly" });
  const [data, setData] = useState(null);
  const [error, setError] = useState("");
  useEffect(() => { let active = true; getAnalytics("insights", filters, token).then((response) => active && setData(response.data)).catch((requestError) => active && setError(requestError.message)); return () => { active = false; }; }, [filters, token]);
  return <div className="page-content analytics-page"><section className="page-header analytics-title"><div><span className="eyebrow">Decision engine</span><h1>Insights and actions</h1><p>Deterministic alerts, observations, and recommendations with supporting evidence. No live AI call is used.</p></div><AnalyticsFilters filters={filters} onChange={setFilters}/></section>{error && <div className="analytics-error">{error}</div>}{!data && !error && <div className="analytics-loading"><span className="spinner"/>Running insight rules…</div>}{data && <><section className="insight-list">{data.insights.length ? data.insights.map((item) => <article className={`insight-card severity-${item.severity}`} key={item.id}><div className="insight-meta"><span>{titleCase(item.type)}</span><span>{titleCase(item.category)}</span><span>{item.severity}</span></div><h2>{item.title}</h2><p>{item.explanation}</p><div className="evidence-box"><strong>Evidence</strong><pre>{JSON.stringify(item.evidence, null, 2)}</pre></div>{item.action && <div className="recommended-action"><strong>Recommended action</strong><span>{item.action}</span></div>}<a href={item.link}>Open relevant analytics →</a></article>) : <div className="analytics-card analytics-empty">No insight rules were triggered for this period.</div>}</section><section className="analytics-card forecast-summary"><div className="analytics-card-heading"><div><span className="eyebrow">Statistical forecast</span><h2>Forecast reliability</h2></div>{data.forecast?.backtest?.ok && <span>{data.forecast.backtest.confidence} confidence</span>}</div>{data.forecast?.ok ? <><p>Method: {data.forecast.method}. Backtest sMAPE: {data.forecast.backtest?.ok ? formatPercent(data.forecast.backtest.smape) : data.forecast.backtest?.reason}.</p><div className="chart-space"><ResponsiveContainer><AreaChart data={data.forecast.points}><CartesianGrid stroke="#1c2730" vertical={false}/><XAxis dataKey="date" tick={{ fill: "#74818b", fontSize: 9 }}/><YAxis tick={{ fill: "#74818b", fontSize: 9 }}/><Tooltip/><Area dataKey="upper" stroke="none" fill="#7cbcff" fillOpacity={0.12}/><Area dataKey="lower" stroke="none" fill="#080b0f"/><Line dataKey="value" stroke="#7cbcff" dot={false}/></AreaChart></ResponsiveContainer></div></> : <div className="analytics-empty">{data.forecast?.reason}</div>}</section></>}<footer className="page-footer"><span>ALPHA / INTELLIGENCE</span><span>Rules, evidence, action</span></footer></div>;
}
